name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight UTC
  push:
    branches:
      - main
      - master
      - dev

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Update dependencies
        run: |
          ncu -u
          npm install

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout dev
          git add -f package.json package-lock.json
          git commit -m "Chore: Update dependencies"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/tauseef-creator/SCD-github-workflow-assignment-02.git HEAD:refs/heads/dev

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          base: master
          title: 'Chore: Update dependencies'
          body: |
            This pull request updates the dependencies of the project.