name: Scheduled Tasks

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day

jobs:
  scheduled_task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Starting Scheduled Task
        run: echo "Starting Scheduled Task..."

      - name: Run Backup Script
        run: ./backup.sh

      - name: Echo Scheduled Task Completed
        run: echo "Scheduled Task Completed!"
